/**
 * OBJ Writer Implementation
 *
 * Exports triangle mesh to Wavefront OBJ format:
 * - Buffered writing for large meshes
 * - Vertex positions (v)
 * - Vertex normals (vn) - optional
 * - Face indices (f)
 * - Material library reference (mtllib)
 * - Material groups (usemtl)
 * - MTL file generation with material colors
 */

#include "../include/obj_io.h"
#include <stdio.h>
#include <string.h>

/* ============================================================================
 * Default Options
 * ============================================================================ */

const ObjExportOptions OBJ_EXPORT_DEFAULTS = {
    .write_normals = true,
    .write_mtl = true,
    .mtl_name = NULL
};

/* ============================================================================
 * Helper Functions
 * ============================================================================ */

/**
 * Extract base name from path (without extension)
 */
static void get_base_name(const char* path, char* base, size_t base_size) {
    const char* last_slash = strrchr(path, '/');
    const char* last_backslash = strrchr(path, '\\');
    const char* name_start = path;

    if (last_slash && last_slash > name_start) name_start = last_slash + 1;
    if (last_backslash && last_backslash > name_start) name_start = last_backslash + 1;

    /* Copy without extension */
    const char* dot = strrchr(name_start, '.');
    size_t len = dot ? (size_t)(dot - name_start) : strlen(name_start);

    if (len >= base_size) len = base_size - 1;
    memcpy(base, name_start, len);
    base[len] = '\0';
}

/**
 * Get directory from path
 */
static void get_directory(const char* path, char* dir, size_t dir_size) {
    const char* last_slash = strrchr(path, '/');
    const char* last_backslash = strrchr(path, '\\');
    const char* dir_end = last_slash > last_backslash ? last_slash : last_backslash;

    if (dir_end) {
        size_t len = (size_t)(dir_end - path + 1);
        if (len >= dir_size) len = dir_size - 1;
        memcpy(dir, path, len);
        dir[len] = '\0';
    } else {
        dir[0] = '\0';
    }
}

/* ============================================================================
 * MTL Writer
 * ============================================================================ */

/**
 * Write MTL file with materials from WorldBrickMap
 */
static ObjIOResult write_mtl_file(const char* mtl_path, const WorldBrickMap* world,
                                  const TriangleMesh* mesh, char* error) {
    FILE* file = fopen(mtl_path, "w");
    if (!file) {
        if (error) snprintf(error, 256, "Cannot create MTL file: %s", mtl_path);
        return OBJ_IO_ERROR_FILE_WRITE;
    }

    fprintf(file, "# MTL file generated by obj_io module\n\n");

    if (world && world->material_count > 0) {
        /* Write materials from world registry */
        for (uint32_t i = 0; i < world->material_count; i++) {
            const MaterialMetadata* mat = &world->materials[i];

            fprintf(file, "newmtl %s\n", mat->name);
            fprintf(file, "Kd %.6f %.6f %.6f\n",
                    mat->diffuse_color.x, mat->diffuse_color.y, mat->diffuse_color.z);
            fprintf(file, "Ka 0.1 0.1 0.1\n");  /* Ambient */
            fprintf(file, "Ks 0.0 0.0 0.0\n");  /* No specular */
            fprintf(file, "Ns 10.0\n");          /* Specular exponent */
            fprintf(file, "illum 1\n\n");        /* Flat shading */
        }
    } else {
        /* Write default material */
        fprintf(file, "newmtl default\n");
        fprintf(file, "Kd 1.0 1.0 1.0\n");
        fprintf(file, "Ka 0.1 0.1 0.1\n");
        fprintf(file, "Ks 0.0 0.0 0.0\n");
        fprintf(file, "Ns 10.0\n");
        fprintf(file, "illum 1\n");
    }

    fclose(file);
    return OBJ_IO_SUCCESS;
}

/* ============================================================================
 * OBJ Writer
 * ============================================================================ */

ObjIOResult obj_export_file(const char* path, const TriangleMesh* mesh,
                            const WorldBrickMap* world,
                            const ObjExportOptions* options, char* error) {
    if (!path || !mesh) {
        if (error) snprintf(error, 256, "Invalid parameters");
        return OBJ_IO_ERROR_INVALID_PARAMETER;
    }

    if (!options) {
        options = &OBJ_EXPORT_DEFAULTS;
    }

    if (mesh->vertex_count == 0 || mesh->face_count == 0) {
        if (error) snprintf(error, 256, "Empty mesh");
        return OBJ_IO_ERROR_EMPTY_MESH;
    }

    /* Determine MTL filename */
    char base_name[256];
    get_base_name(path, base_name, sizeof(base_name));

    char mtl_filename[280];
    if (options->mtl_name) {
        strncpy(mtl_filename, options->mtl_name, sizeof(mtl_filename) - 1);
    } else {
        snprintf(mtl_filename, sizeof(mtl_filename), "%s.mtl", base_name);
    }
    mtl_filename[sizeof(mtl_filename) - 1] = '\0';

    /* Write MTL file if requested */
    if (options->write_mtl) {
        char dir[512];
        char mtl_path[768];
        get_directory(path, dir, sizeof(dir));
        snprintf(mtl_path, sizeof(mtl_path), "%s%s", dir, mtl_filename);

        ObjIOResult mtl_result = write_mtl_file(mtl_path, world, mesh, error);
        if (mtl_result != OBJ_IO_SUCCESS) {
            return mtl_result;
        }
    }

    /* Open OBJ file */
    FILE* file = fopen(path, "w");
    if (!file) {
        if (error) snprintf(error, 256, "Cannot create OBJ file: %s", path);
        return OBJ_IO_ERROR_FILE_WRITE;
    }

    /* Write header */
    fprintf(file, "# OBJ file generated by obj_io module\n");
    fprintf(file, "# Vertices: %u, Faces: %u\n\n", mesh->vertex_count, mesh->face_count);

    /* Material library reference */
    if (options->write_mtl) {
        fprintf(file, "mtllib %s\n\n", mtl_filename);
    }

    /* Write vertices */
    for (uint32_t i = 0; i < mesh->vertex_count; i++) {
        fprintf(file, "v %.6f %.6f %.6f\n", mesh->vx[i], mesh->vy[i], mesh->vz[i]);
    }
    fprintf(file, "\n");

    /* Write normals if present and requested */
    bool has_normals = options->write_normals && mesh->has_normals;
    if (has_normals) {
        for (uint32_t i = 0; i < mesh->vertex_count; i++) {
            fprintf(file, "vn %.6f %.6f %.6f\n", mesh->nx[i], mesh->ny[i], mesh->nz[i]);
        }
        fprintf(file, "\n");
    }

    /* Write faces grouped by material */
    if (options->write_mtl && world && world->material_count > 0) {
        /* Group faces by material */
        uint8_t current_mat = 255; /* Invalid initial value */

        for (uint32_t f = 0; f < mesh->face_count; f++) {
            uint8_t mat = mesh->face_mat[f];

            /* Write usemtl if material changed */
            if (mat != current_mat) {
                const char* mat_name = "default";
                if (mat < world->material_count) {
                    mat_name = world->materials[mat].name;
                }
                fprintf(file, "\nusemtl %s\n", mat_name);
                current_mat = mat;
            }

            /* Write face (1-indexed) */
            uint32_t base = f * 3;
            uint32_t v0 = mesh->face_v[base + 0] + 1;
            uint32_t v1 = mesh->face_v[base + 1] + 1;
            uint32_t v2 = mesh->face_v[base + 2] + 1;

            if (has_normals) {
                fprintf(file, "f %u//%u %u//%u %u//%u\n", v0, v0, v1, v1, v2, v2);
            } else {
                fprintf(file, "f %u %u %u\n", v0, v1, v2);
            }
        }
    } else {
        /* Write faces without material groups */
        if (options->write_mtl) {
            fprintf(file, "usemtl default\n");
        }

        for (uint32_t f = 0; f < mesh->face_count; f++) {
            uint32_t base = f * 3;
            uint32_t v0 = mesh->face_v[base + 0] + 1;
            uint32_t v1 = mesh->face_v[base + 1] + 1;
            uint32_t v2 = mesh->face_v[base + 2] + 1;

            if (has_normals) {
                fprintf(file, "f %u//%u %u//%u %u//%u\n", v0, v0, v1, v1, v2, v2);
            } else {
                fprintf(file, "f %u %u %u\n", v0, v1, v2);
            }
        }
    }

    fclose(file);
    return OBJ_IO_SUCCESS;
}

/* ============================================================================
 * High-Level world_to_obj
 * ============================================================================ */

ObjIOResult world_to_obj(const WorldBrickMap* world, const char* path, char* error) {
    if (!world || !path) {
        if (error) snprintf(error, 256, "Invalid parameters");
        return OBJ_IO_ERROR_INVALID_PARAMETER;
    }

    /* Use the world's arena for temporary mesh */
    Arena* arena = world->arena;
    if (!arena) {
        if (error) snprintf(error, 256, "World has no arena");
        return OBJ_IO_ERROR_INVALID_PARAMETER;
    }

    /* Extract mesh using Marching Cubes */
    TriangleMesh* mesh = NULL;
    ObjIOResult result = sdf_to_mesh(arena, world, &MARCHING_CUBES_DEFAULTS, &mesh, error);
    if (result != OBJ_IO_SUCCESS) {
        return result;
    }

    /* Export to OBJ */
    return obj_export_file(path, mesh, world, &OBJ_EXPORT_DEFAULTS, error);
}

/* ============================================================================
 * Mesh Comparison
 * ============================================================================ */

MeshCompareResult mesh_compare(Arena* arena, const TriangleMesh* mesh_a,
                               const TriangleMesh* mesh_b, float tolerance) {
    MeshCompareResult result = {0};
    result.passed = false;

    if (!arena || !mesh_a || !mesh_b) {
        return result;
    }

    if (mesh_a->face_count == 0 || mesh_b->face_count == 0) {
        return result;
    }

    /* Build BVH for mesh_b */
    MeshBVH* bvh_b = bvh_build(arena, mesh_b);
    if (!bvh_b) {
        return result;
    }

    /* Sample vertices from mesh_a and find distances to mesh_b */
    uint32_t sample_count = mesh_a->vertex_count;
    float max_dist = 0.0f;
    double sum_dist = 0.0;
    double sum_dist_sq = 0.0;

    for (uint32_t i = 0; i < mesh_a->vertex_count; i++) {
        Vec3 p = VEC3(mesh_a->vx[i], mesh_a->vy[i], mesh_a->vz[i]);
        float dist = bvh_closest_point(bvh_b, mesh_b, p, NULL, NULL);

        if (dist > max_dist) max_dist = dist;
        sum_dist += dist;
        sum_dist_sq += (double)dist * dist;
    }

    /* Also sample from mesh_b to mesh_a for symmetric Hausdorff */
    MeshBVH* bvh_a = bvh_build(arena, mesh_a);
    if (bvh_a) {
        for (uint32_t i = 0; i < mesh_b->vertex_count; i++) {
            Vec3 p = VEC3(mesh_b->vx[i], mesh_b->vy[i], mesh_b->vz[i]);
            float dist = bvh_closest_point(bvh_a, mesh_a, p, NULL, NULL);

            if (dist > max_dist) max_dist = dist;
            sum_dist += dist;
            sum_dist_sq += (double)dist * dist;
        }
        sample_count += mesh_b->vertex_count;
    }

    result.hausdorff_distance = max_dist;
    result.mean_distance = (float)(sum_dist / sample_count);
    result.rms_distance = (float)sqrt(sum_dist_sq / sample_count);
    result.sample_count = sample_count;
    result.passed = (max_dist <= tolerance);

    return result;
}
